In [1]:
from sklearn import tree
import numpy as np
import pandas as pd

In [2]:
datasets = pd.read_csv("heart_failure_clinical_records_dataset.csv")

In [3]:
datasets.head()

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0  75.0        0                       582         0                 20   
1  55.0        0                      7861         0                 38   
2  65.0        0                       146         0                 20   
3  50.0        1                       111         0                 20   
4  65.0        1                       160         1                 20   

   high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                    1  265000.00               1.9           130    1   
1                    0  263358.03               1.1           136    1   
2                    0  162000.00               1.3           129    1   
3                    0  210000.00               1.9           137    1   
4                    0  327000.00               2.7           116    0   

   smoking  time  DEATH_EVENT  
0        0     4            1  
1        0     6            1  
2        1     7            1  
3        0     7            1  
4        0     8            1

In [4]:
# Merubah kelas/kolom dari String ke Unique-Integer
#datasets['time'] = pd.factorize(datasets.time)[0]

In [5]:
#datasets.tail()

In [6]:
# # # Menghapus kolom ID
# datasets = datasets.drop(labels="Pregnancies", axis=1)

In [7]:
#Merubah dataframe ke array numpy
datasets = datasets.to_numpy() 

In [8]:
print(datasets)

[[7.500e+01 0.000e+00 5.820e+02 ... 0.000e+00 4.000e+00 1.000e+00]
 [5.500e+01 0.000e+00 7.861e+03 ... 0.000e+00 6.000e+00 1.000e+00]
 [6.500e+01 0.000e+00 1.460e+02 ... 1.000e+00 7.000e+00 1.000e+00]
 ...
 [4.500e+01 0.000e+00 2.060e+03 ... 0.000e+00 2.780e+02 0.000e+00]
 [4.500e+01 0.000e+00 2.413e+03 ... 1.000e+00 2.800e+02 0.000e+00]
 [5.000e+01 0.000e+00 1.960e+02 ... 1.000e+00 2.850e+02 0.000e+00]]


In [17]:
#Membagi datasets => 400 baris data untuk training dan 100 baris data untuk testing
dataTraining = np.concatenate((datasets[0:120, :], datasets[150:269, :]), axis=0)
dataTesting = np.concatenate((datasets[120:150, :], datasets[269:299, :]), axis=0)

In [18]:
print(dataTraining)
len(dataTraining)

[[7.500e+01 0.000e+00 5.820e+02 ... 0.000e+00 4.000e+00 1.000e+00]
 [5.500e+01 0.000e+00 7.861e+03 ... 0.000e+00 6.000e+00 1.000e+00]
 [6.500e+01 0.000e+00 1.460e+02 ... 1.000e+00 7.000e+00 1.000e+00]
 ...
 [5.500e+01 0.000e+00 1.199e+03 ... 1.000e+00 2.410e+02 1.000e+00]
 [5.600e+01 1.000e+00 1.350e+02 ... 0.000e+00 2.440e+02 0.000e+00]
 [4.500e+01 0.000e+00 5.820e+02 ... 0.000e+00 2.440e+02 0.000e+00]]


239

In [19]:
print(dataTesting)
len(dataTesting)

[[6.0000000e+01 1.0000000e+00 7.3700000e+02 0.0000000e+00 6.0000000e+01
  1.0000000e+00 2.1000000e+05 1.5000000e+00 1.3500000e+02 1.0000000e+00
  1.0000000e+00 9.5000000e+01 0.0000000e+00]
 [6.6000000e+01 1.0000000e+00 6.8000000e+01 1.0000000e+00 3.8000000e+01
  1.0000000e+00 1.6200000e+05 1.0000000e+00 1.3600000e+02 0.0000000e+00
  0.0000000e+00 9.5000000e+01 0.0000000e+00]
 [6.0000000e+01 0.0000000e+00 9.6000000e+01 1.0000000e+00 3.8000000e+01
  0.0000000e+00 2.2800000e+05 7.5000000e-01 1.4000000e+02 0.0000000e+00
  0.0000000e+00 9.5000000e+01 0.0000000e+00]
 [6.0000000e+01 1.0000000e+00 5.8200000e+02 0.0000000e+00 3.0000000e+01
  1.0000000e+00 1.2700000e+05 9.0000000e-01 1.4500000e+02 0.0000000e+00
  0.0000000e+00 9.5000000e+01 0.0000000e+00]
 [6.0000000e+01 0.0000000e+00 5.8200000e+02 0.0000000e+00 4.0000000e+01
  0.0000000e+00 2.1700000e+05 3.7000000e+00 1.3400000e+02 1.0000000e+00
  0.0000000e+00 9.6000000e+01 1.0000000e+00]
 [4.3000000e+01 1.0000000e+00 3.5800000e+02 0.0000000e+

60

In [22]:
#Memecah dataset ke input label
inputTraining = dataTraining[:,0:12]
inputTesting = dataTesting[:,0:12]
labelTraining = dataTraining[:,12]
labelTesting = dataTesting[:,12]
print(labelTraining)
len(labelTraining)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0.
 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.]


239

In [23]:
#Mendefinisikan decision tree classifier
model = tree.DecisionTreeClassifier()

In [24]:
#Mentraining model
model =  model.fit(inputTraining, labelTraining)

In [25]:
#Memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Hasil Prediksi :  [1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [26]:
#Menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, " Data")
print("Prediksi Salah : ", prediksiSalah, " Data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar :  51  Data
Prediksi Salah :  9  Data
Akurasi :  85.0 %
